
version: '3'
services:
  server:
    build: .
    image: k8e-server
    command: /k8e master
    privileged: true
    ports:
      - 6445:6443

  agent:
    build: .
    image: k8e-server
    command: /k8e agent --master=http://server:6445
    privileged: true
