version: '3'
services:
  server:
    build: .
    image: k8e-server
    command: /k8e server --disable-agent=true
    tmpfs:
    - /run
    - /var/run
    privileged: true
    ports:
      - 6444:6444
      - 8080:8080
    volumes:
    - k8s-server:/var/lib/k8e
    # This is just so that we get the kubeconfig file out
    - .:/output

  agent:
    image: k8e-server
    command: /k8e agent --server=https://server:6444
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server

volumes:
  k8s-server: {}