version: '3'
services:
  server:
    build: .
    image: k8e-server
    command: /k8e server
    privileged: true
    ports:
      - 6444:6444
      - 8080:8080

  agent:
    image: k8e-server
    command: /k8e agent --server=https://server:6444
    privileged: true
