name: Build for k8e

on:
  push:
    branches:
      - dev

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: check depends
      run: sudo apt-get install -y libseccomp-dev

    - name: generate resources
      run: make generate

    - name: Test
      run: go get -u github.com/rakyll/gotest && go mod vendor && gotest -v ./...