on:
  push:
    branches:
      - dev
name: Build Test
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: check depends
      run: sudo apt-get install -y libseccomp-dev
    - name: generate resources
      run: make generate
    - name: Test
      run: go get -u github.com/rakyll/gotest && go mod vendor && gotest -v ./...