name: Go for k8e

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Release
    runs-on: [ubuntu-latest]
    env:
      DRONE_TAG: v1.19.14+k8e2
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: check depends
      run: sudo apt-get install -y libseccomp-dev

    - name: generate resources
      run: make generate

    - name: Test
      run: go get -u github.com/rakyll/gotest && go mod vendor && gotest -v ./...

    - name: package bin
      run: SKIP_VALIDATE=true make

    - name: Deploy to qiniu
      uses: saltbo/uptoc@master
      with:
        driver: qiniu
        region: ap-southeast-1
        bucket: k8e
        exclude: .cache,test
        dist: dist/artifacts
      env:
        UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
        UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
